In [ ]:
# 1. CREATING NUMPY ARRAYS

import numpy as np

In [ ]:
years_exp = np.array([1, 3, 5, 7 ,10])
print("Years of Experience:", years_exp)

Years of Experience: [ 1  3  5  7 10]


In [41]:
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]


In [42]:
zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
# 2. ARRAYS OPERATION

# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)


Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [44]:
# 3. Indexing and Slicing

# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2]) # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [45]:
# 4. Reshaping and Dimensions

# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [46]:
# 5. Broadcasting in NumPy

# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus:\n", salaries_with_bonus)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [47]:
# 6. Statistical Operations

# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 Min salary: 50
Sum of all salaries: 450


In [48]:
# 7. NumPy Functions on Arrays

# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)


Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [49]:
# 8. Integrating NumPy and Pandas for Analysis

import pandas as pd
# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

# Step 4: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

Generated Data:
 

    X   Y   Z
0   5  43   9
1  15  44   4
2  45  38   5
3  26  21  36
4  20  46  31
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0   5  43   9  1.609438  6.557439
1  15  44   4  2.708050  6.633250
2  45  38   5  3.806662  6.164414
3  26  21  36  3.258097  4.582576
4  20  46  31  2.995732  6.782330
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.349230 -0.001099  0.935003 -0.325775
Y      -0.349230  1.000000 -0.529593 -0.388511  0.999260
Z      -0.001099 -0.529593  1.000000  0.202354 -0.555652
Log_X   0.935003 -0.388511  0.202354  1.000000 -0.376222
Sqrt_Y -0.325775  0.999260 -0.555652 -0.376222  1.000000


In [50]:
# 9. Importing and Summarizing Data Using Pandas

# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file back into a new DataFrame
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']


Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y
0   5  43   9  1.609438  6.557439
1  15  44   4  2.708050  6.633250
2  45  38   5  3.806662  6.164414
3  26  21  36  3.258097  4.582576
4  20  46  31  2.995732  6.782330
Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y
count   5.000000   5.000000   5.000000  5.000000  5.000000
mean   22.200000  38.400000  17.000000  2.875596  6.144002
std    14.889594  10.163661  15.280707  0.815299  0.902251
min     5.000000  21.000000   4.000000  1.609438  4.582576
25%    15.000000  38.000000   5.000000  2.708050  6.164414
50%    20.000000  43.000000   9.000000  2.995732  6.557439
75%    26.000000  44.000000  31.000000  3.258097  6.633250
max    45.000000  46.000000  36.000000  3.806662  6.782330
Column Means:
 X         22.200000
Y         38.400000
Z         17.000000
Log_X      2.875596
Sqrt_Y     6.144002
dtype: float64
Column Standard Deviations:
 X         14.889594
Y         1

In [1]:
# NO.1

import numpy as np
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
data = np.random.randint(1, int(STUDENT_ID.split('-')[2]) % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Jedrian Ilagan's Array: [74 83 99 81 43 55  1  7 90 84]
Mean: 61.7 Std Dev: 32.76904026669075


In [ ]:
years_exp = np.array([1, 3, 5, 7 ,10])
print("Years of Experience:", years_exp)

Years of Experience: [ 1  3  5  7 10]


In [3]:
# NO.2

import numpy as np
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID[-4:]))
matrix = np.random.randint(1, int(STUDENT_ID[-4:]) % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)


Jedrian Ilagan's Matrix:
 [[10 19  3 17]
 [11  1  7 10]
 [15 12  7 11]]
Row sums: [49 29 45]
Column sums: [36 32 17 38]


In [4]:
# NO.3 

import numpy as np
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
arr3d = np.random.randint(0, int(STUDENT_ID.split('-')[2]) % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)
slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)


Jedrian Ilagan's 3D Array:
 [[[ 9 18  2]
  [16 10  0]
  [ 6 19  9]]

 [[14 11  6]
  [10  1  4]
  [17  1 18]]

 [[18 12  4]
  [ 7 12 13]
  [14 18  0]]]
Slice[:,1,:]:
 [[16 10  0]
 [10  1  4]
 [ 7 12 13]]


In [5]:
# NO.4
import numpy as np
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
x = np.random.randint(1, int(STUDENT_ID.split('-')[2]) % 100 + 50, size=10)
filtered = x[(x>int(STUDENT_ID.split('-')[2])%50) & (x<int(STUDENT_ID.split('-')[2])%100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Jedrian Ilagan's Original: [74 83 99 81 43 55  1  7 90 84]
Filtered subset: [43  1  7]


In [6]:
# NO.5  

import numpy as np
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
A = np.random.randint(1, int(STUDENT_ID.split('-')[2]) % 50 + 20, size=(2,2))
B = np.random.randint(1, int(STUDENT_ID.split('-')[2]) % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[10 19]
 [ 3 17]]
Matrix B:
 [[11  1]
 [ 7 10]]
A @ B:
 [[243 200]
 [152 173]]
Determinant of A: 113.00000000000003


In [7]:
# NO.6

import numpy as np
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Jedrian Ilagan's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [8]:
#  NO.7

import numpy as np
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
arr = np.random.randint(1, int(STUDENT_ID.split('-')[2]) % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Jedrian Ilagan's Modified 4x4 Array:
 [[ 0 19  0 17]
 [11  1  7 10]
 [ 0 12  0 11]
 [ 2  5 18  2]]


In [9]:
# NO.8

import numpy as np
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
scores = np.random.randint(0, int(STUDENT_ID.split('-')[2]) % 100 + 50, 10)
grades = np.where(scores>=int(STUDENT_ID.split('-')[2])%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Jedrian Ilagan's Scores: [73 82 98 80 42 54  0  6 89 83]
Grades: ['Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Fail' 'Pass' 'Pass']


In [10]:
# NO.9

import numpy as np
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
arr = np.random.randint(1, int(STUDENT_ID.split('-')[2]) % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)


Original array:
 [[10 19  3 17]
 [11  1  7 10]
 [15 12  7 11]]
Flattened: [10 19  3 17 11  1  7 10 15 12  7 11]
Transposed:
 [[10 11 15]
 [19  1 12]
 [ 3  7  7]
 [17 10 11]]


In [11]:
# NO.10

import numpy as np
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
arr = np.random.randint(1, int(STUDENT_ID.split('-')[2]) % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[-1 19  3]
 [17 11  1]
 [ 7 -1 15]]


In [12]:
# NO.11

import numpy as np
import pandas as pd
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(int(STUDENT_ID.split('-')[2])%50,
int(STUDENT_ID.split('-')[2])%100+50,5),
 'YearsCodePro': np.random.randint(0, int(STUDENT_ID.split('-')[2])%20+10,5)
})
print(df)

             Name  Score  YearsCodePro
0  Jedrian Ilagan     73             0
1  Jedrian Ilagan     82             6
2  Jedrian Ilagan     98            19
3  Jedrian Ilagan     80             9
4  Jedrian Ilagan     42            14


In [13]:
# NO.12

import numpy as np
import pandas as pd
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
# Corrected to use a functional salary range, e.g., 40000 to 150000
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)


EdLevel
Bachelor     52501.5
Master       81086.0
PhD         121652.0
Name: ConvertedComp, dtype: float64


In [14]:
# NO.13

import numpy as np
import pandas as pd
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)


       Country  ConvertedComp
2           UK         121652
1          USA         103442
3       Canada          59682
4      Germany          58730
0  Philippines          45321


In [15]:
# NO.14

import numpy as np
import pandas as pd
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
df = pd.DataFrame({
 'Name':[STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, int(STUDENT_ID.split('-')[2])%20+10,5)
})
high_exp = df[df['YearsCodePro']>int(STUDENT_ID.split('-')[2])%10]
print(high_exp)


             Name  YearsCodePro
0  Jedrian Ilagan             9
1  Jedrian Ilagan            18
2  Jedrian Ilagan             2
3  Jedrian Ilagan            16
4  Jedrian Ilagan            10


In [17]:
# NO.15

import numpy as np
import pandas as pd

STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"

# Convert ID to a numeric seed
seed_value = int(STUDENT_ID.split('-')[-1])
np.random.seed(seed_value)

# Include values up to 200000 so last bin is usable
df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 200001, 5)
})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)

print(df)

   ConvertedComp   Bracket
0          45321     0-50k
1         190754     >150k
2          58730   50-100k
3         112118  100-150k
4         194374     >150k


In [18]:
# NO.16

import numpy as np
import pandas as pd
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[-1]))
# Original Code Issue:
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)
# -> np.random.randint(12345, 12345, 5) which is a zero-length range.
# Corrected Code: Using a functional salary range (40000 to 150000)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)


   ConvertedComp    LogComp
0          45321  10.721526
1         103442  11.546766
2         121652  11.708920
3          59682  10.996786
4          58730  10.980706


In [19]:
# NO.17

import numpy as np
import pandas as pd
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, int(STUDENT_ID.split('-')[2])%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
corr_matrix = df.corr()
print(corr_matrix)


               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.438059
ConvertedComp      0.438059       1.000000


In [20]:
# NO.18

import numpy as np
import pandas as pd
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
df = pd.DataFrame({
'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor   52501.5   52501.5  10154.760485
1    Master   81086.0   81086.0  31616.158400
2       PhD  121652.0  121652.0           NaN


In [21]:
# NO.19

import numpy as np
import pandas as pd
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
threshold = 110000
# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0          45321      No
1         103442      No
2         121652     Yes
3          59682      No
4          58730      No


In [22]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = "TUPM-25-3550"
np.random.seed(int(STUDENT_ID.split('-')[2]))
df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada        59682.0   59682
Germany       58730.0   58730
Philippines   45321.0   45321
UK           121652.0  121652
USA          103442.0  103442


In [5]:
import pandas as pd

In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:\\Users\\Jed\\Desktop\\Comprog_Lab\\lab6_NUMBYPANDAS_Ilagan\\Most Popular Programming Languages.csv")
print(df.head())

     Month  Python Worldwide(%)  JavaScript Worldwide(%)  Java Worldwide(%)  \
0  2004-01                   30                       98                 96   
1  2004-02                   29                       98                 97   
2  2004-03                   28                      100                100   
3  2004-04                   28                       98                 97   
4  2004-05                   28                       91                 99   

   C# Worldwide(%)  PhP Worldwide(%)  Flutter Worldwide(%)  \
0               76               100                     6   
1               86                99                     6   
2               87                97                     5   
3               89               100                     6   
4               84                92                     6   

   React Worldwide(%)  Swift Worldwide(%)  TypeScript Worldwide(%)  \
0                   1                   9                        2   
1           

In [8]:
STUDENT_ID = "TUPM-25-3550"

In [9]:
languages = ['C#', 'Flutter', 'Java', 'JavaScript', 'Matlab',
             'PhP', 'Python', 'React', 'Swift', 'TypeScript']

index = 550 % 10  # = 0
assigned_language = languages[index]

In [16]:
# =========================
# EXERCISE 1
# =========================

import numpy as np
import pandas as pd

STUDENT_NAME = "Your Name"
STUDENT_ID = 3550   # last 3 digits

# file path
file_path = r"C:\Users\Jed\Desktop\Comprog_Lab\lab6_NUMBYPANDAS_Ilagan\Most Popular Programming Languages.csv"

df = pd.read_csv(file_path)

# convert date
df['Month'] = pd.to_datetime(df['Month'])

# language list
languages = sorted(['C#', 'Flutter', 'Java', 'JavaScript', 'Matlab',
                    'PhP', 'Python', 'React', 'Swift', 'TypeScript'])

index = STUDENT_ID % 10
assigned_language = languages[index]

print("Assigned Language:", assigned_language)

# check columns first
print(df.columns)

# adjust if needed
lang_col = assigned_language + " Worldwide (%)"

data = df[['Month', lang_col]].copy()
data.columns = ['Month', 'Popularity']

# calculations
data['Growth_Rate'] = data['Popularity'].pct_change() * 100
data['Moving_Avg'] = data['Popularity'].rolling(6).mean()
data['Moving_STD'] = data['Popularity'].rolling(6).std()

# classify
conditions = [
    (data['Growth_Rate'] > 5),
    (data['Growth_Rate'] < -5),
    (data['Growth_Rate'].between(-5, 5))
]

choices = ['Growth', 'Decline', 'Stable']

data['Phase'] = np.select(conditions, choices, default='Stable')

# outputs
print("\n--- TABLE ---")
print(data.head(10))

print("\n--- SUMMARY ---")
print(data['Popularity'].describe())

print("\n--- PHASE COUNT ---")
print(data['Phase'].value_counts())

# performance
initial = data['Popularity'].iloc[0]
final = data['Popularity'].iloc[-1]

growth_percent = ((final - initial) / initial) * 100

print("\nInitial:", initial)
print("Final:", final)
print("Overall Growth %:", growth_percent)



Assigned Language: C#
Index(['Month', 'Python Worldwide(%)', 'JavaScript Worldwide(%)',
       'Java Worldwide(%)', 'C# Worldwide(%)', 'PhP Worldwide(%)',
       'Flutter Worldwide(%)', 'React Worldwide(%)', 'Swift Worldwide(%)',
       'TypeScript Worldwide(%)', 'Matlab Worldwide(%)'],
      dtype='str')


KeyError: "['C# Worldwide (%)'] not in index"

In [12]:
print(df.columns)

Index(['Month', 'Python Worldwide(%)', 'JavaScript Worldwide(%)',
       'Java Worldwide(%)', 'C# Worldwide(%)', 'PhP Worldwide(%)',
       'Flutter Worldwide(%)', 'React Worldwide(%)', 'Swift Worldwide(%)',
       'TypeScript Worldwide(%)', 'Matlab Worldwide(%)'],
      dtype='str')


In [15]:
# -------------------------
# AUTO-DETECT COLUMN (FIX)
# -------------------------
lang_col = None

for col in df.columns:
    if assigned_language.lower() in col.lower():
        lang_col = col
        break

print("Detected column:", lang_col)

# safety check
if lang_col is None:
    print("ERROR: Column not found. Check column names below:")
    print(df.columns)
else:
    data = df[['Month', lang_col]].copy()
    data.columns = ['Month', 'Popularity']

Detected column: C# Worldwide(%)


In [ ]:
# =========================
# EXERCISE 1 (FIXED)
# =========================

import numpy as np
import pandas as pd

STUDENT_NAME = "Jedrian Ilagan"
STUDENT_ID = 3550

file_path = r"C:\Users\Jed\Desktop\Comprog_Lab\lab6_NUMBYPANDAS_Ilagan\Most Popular Programming Languages.csv"

df = pd.read_csv(file_path)

# convert date
df['Month'] = pd.to_datetime(df['Month'])

# language assignment
languages = sorted(['C#', 'Flutter', 'Java', 'JavaScript', 'Matlab',
                    'PhP', 'Python', 'React', 'Swift', 'TypeScript'])

index = STUDENT_ID % 10
assigned_language = languages[index]

print("Assigned Language:", assigned_language)

# -------------------------
# AUTO DETECT COLUMN
# -------------------------
lang_col = None
for col in df.columns:
    if assigned_language.lower() in col.lower():
        lang_col = col
        break

print("Using column:", lang_col)

# safety check
if lang_col is None:
    print("ERROR: Column not found")
    print(df.columns)
else:
    data = df[['Month', lang_col]].copy()
    data.columns = ['Month', 'Popularity']

    # calculations
    data['Growth_Rate'] = data['Popularity'].pct_change() * 100
    data['Moving_Avg'] = data['Popularity'].rolling(6).mean()
    data['Moving_STD'] = data['Popularity'].rolling(6).std()

    # classification
    conditions = [
        (data['Growth_Rate'] > 5),
        (data['Growth_Rate'] < -5),
        (data['Growth_Rate'].between(-5, 5))
    ]

    choices = ['Growth', 'Decline', 'Stable']
    data['Phase'] = np.select(conditions, choices, default='Stable')

    # outputs
    print("\n--- TABLE ---")
    print(data.head(10))

    print("\n--- SUMMARY ---")
    print(data['Popularity'].describe())

    print("\n--- PHASE COUNT ---")
    print(data['Phase'].value_counts())

    # performance
    initial = data['Popularity'].iloc[0]
    final = data['Popularity'].iloc[-1]
    growth_percent = ((final - initial) / initial) * 100

    print("\nInitial:", initial)
    print("Final:", final)
    print("Overall Growth %:", growth_percent)

Assigned Language: C#
Using column: C# Worldwide(%)

--- TABLE ---
       Month  Popularity  Growth_Rate  Moving_Avg  Moving_STD    Phase
0 2004-01-01          76          NaN         NaN         NaN   Stable
1 2004-02-01          86    13.157895         NaN         NaN   Growth
2 2004-03-01          87     1.162791         NaN         NaN   Stable
3 2004-04-01          89     2.298851         NaN         NaN   Stable
4 2004-05-01          84    -5.617978         NaN         NaN  Decline
5 2004-06-01          97    15.476190   86.500000    6.833740   Growth
6 2004-07-01          98     1.030928   90.166667    5.913262   Stable
7 2004-08-01          95    -3.061224   91.666667    5.785038   Stable
8 2004-09-01          97     2.105263   93.333333    5.609516   Stable
9 2004-10-01          90    -7.216495   93.500000    5.468089  Decline

--- SUMMARY ---
count    249.000000
mean      59.626506
std       20.330958
min       27.000000
25%       45.000000
50%       57.000000
75%       78.00

In [18]:
# =========================
# EXERCISE 2 (FIXED)
# =========================

import numpy as np
import pandas as pd

STUDENT_ID = 3550

file_path = r"C:\Users\Jed\Desktop\Comprog_Lab\lab6_NUMBYPANDAS_Ilagan\Most Popular Programming Languages.csv"

df = pd.read_csv(file_path)
df['Month'] = pd.to_datetime(df['Month'])

languages = sorted(['C#', 'Flutter', 'Java', 'JavaScript', 'Matlab',
                    'PhP', 'Python', 'React', 'Swift', 'TypeScript'])

index = STUDENT_ID % 10
assigned_language = languages[index]

# auto detect column
lang_col = None
for col in df.columns:
    if assigned_language.lower() in col.lower():
        lang_col = col
        break

print("Using column:", lang_col)

if lang_col is None:
    print(df.columns)
else:
    data = df[['Month', lang_col]].copy()
    data.columns = ['Month', 'Popularity']

    # calculations
    data['Growth_Rate'] = data['Popularity'].pct_change() * 100
    data['Moving_Avg'] = data['Popularity'].rolling(6).mean()
    data['Moving_STD'] = data['Popularity'].rolling(6).std()

    # stats
    mean_growth = np.mean(data['Growth_Rate'].dropna())
    std_growth = np.std(data['Growth_Rate'].dropna())

    # lifecycle classification
    conditions = [
        (data['Growth_Rate'] > mean_growth),
        (abs(data['Growth_Rate']) <= 1),
        (data['Growth_Rate'] < -std_growth),
        (data['Growth_Rate'] > 0)
    ]

    choices = ['Growth', 'Maturity', 'Decline', 'Introduction']

    data['Lifecycle_Phase'] = np.select(conditions, choices, default='Stable')

    print("\n--- LIFECYCLE TABLE ---")
    print(data.head(10))

    print("\n--- COUNTS ---")
    print(data['Lifecycle_Phase'].value_counts())

Using column: C# Worldwide(%)

--- LIFECYCLE TABLE ---
       Month  Popularity  Growth_Rate  Moving_Avg  Moving_STD Lifecycle_Phase
0 2004-01-01          76          NaN         NaN         NaN          Stable
1 2004-02-01          86    13.157895         NaN         NaN          Growth
2 2004-03-01          87     1.162791         NaN         NaN          Growth
3 2004-04-01          89     2.298851         NaN         NaN          Growth
4 2004-05-01          84    -5.617978         NaN         NaN          Stable
5 2004-06-01          97    15.476190   86.500000    6.833740          Growth
6 2004-07-01          98     1.030928   90.166667    5.913262          Growth
7 2004-08-01          95    -3.061224   91.666667    5.785038          Stable
8 2004-09-01          97     2.105263   93.333333    5.609516          Growth
9 2004-10-01          90    -7.216495   93.500000    5.468089         Decline

--- COUNTS ---
Lifecycle_Phase
Growth     135
Stable      73
Decline     41
Name: coun

In [19]:
# =========================
# EXERCISE 3 (FIXED)
# =========================

import numpy as np
import pandas as pd

STUDENT_ID = 3550

file_path = r"C:\Users\Jed\Desktop\Comprog_Lab\lab6_NUMBYPANDAS_Ilagan\Most Popular Programming Languages.csv"

df = pd.read_csv(file_path)

languages = sorted(['C#', 'Flutter', 'Java', 'JavaScript', 'Matlab',
                    'PhP', 'Python', 'React', 'Swift', 'TypeScript'])

index = STUDENT_ID % 10

lang1 = languages[index]
lang2 = languages[(index + 1) % 10]

print("Language 1:", lang1)
print("Language 2:", lang2)

# auto detect columns
col1 = None
col2 = None

for col in df.columns:
    if lang1.lower() in col.lower():
        col1 = col
    if lang2.lower() in col.lower():
        col2 = col

print("Using:", col1, "and", col2)

if col1 is None or col2 is None:
    print("Check column names:")
    print(df.columns)
else:
    data1 = df[col1]
    data2 = df[col2]

    # stats
    print("\nMean 1:", np.mean(data1))
    print("Mean 2:", np.mean(data2))

    print("Std 1:", np.std(data1))
    print("Std 2:", np.std(data2))

    # correlation
    corr = np.corrcoef(data1, data2)[0,1]
    print("\nCorrelation:", corr)

    # dominance
    count = np.sum(data1 > data2)
    total = len(data1)

    dominance_ratio = (count / total) * 100
    print("Dominance Ratio:", dominance_ratio)

Language 1: C#
Language 2: Flutter
Using: C# Worldwide(%) and Flutter Worldwide(%)

Mean 1: 59.626506024096386
Mean 2: 22.6425702811245
Std 1: 20.290091460782318
Std 2: 28.311888086955157

Correlation: -0.6764361401372501
Dominance Ratio: 77.91164658634538
